package com.didimlog.application.template

/**
 * 회고 템플릿 상수 및 템플릿 생성 로직을 담당하는 객체
 * 템플릿 문자열을 관리하여 서비스 로직과 분리한다.
 */
object RetrospectiveTemplates {

    /**
     * 간단한 성공 회고 템플릿을 생성한다.
     */
    fun generateSimpleSuccess(title: String, markdownLanguage: String, code: String, solveTime: String?): String {
        return buildString {
            appendLine("# 🏆 $title")
            appendLine()
            if (solveTime != null && solveTime.isNotBlank()) {
                appendLine("⏱️ **풀이 소요 시간:** $solveTime")
                appendLine()
            }
            appendLine("## 🔑 핵심 로직 (Key Logic)")
            appendLine()
            appendLine("- 풀이의 핵심 공식이나 접근법을 한 줄로 적어주세요.")
            appendLine()
            appendLine("## 💡 오늘의 배움 (Learnings)")
            appendLine()
            appendLine("- 실수했거나 새로 알게 된 점을 적어주세요.")
            appendLine()
            appendLine("## 제출한 코드")
            appendLine()
            appendLine("```$markdownLanguage")
            append(code)
            appendLine()
            appendLine("```")
            appendLine()
            appendLine("---")
            appendLine("Generated by DidimLog")
        }
    }

    /**
     * 간단한 실패 회고 템플릿을 생성한다.
     */
    fun generateSimpleFailure(title: String, markdownLanguage: String, code: String, errorMessage: String, solveTime: String?): String {
        return buildString {
            appendLine("# 💥 $title")
            appendLine()
            if (solveTime != null && solveTime.isNotBlank()) {
                appendLine("⏱️ **풀이 소요 시간:** $solveTime")
                appendLine()
            }
            appendLine("## 🔑 핵심 로직 (Key Logic)")
            appendLine()
            appendLine("- 풀이의 핵심 공식이나 접근법을 한 줄로 적어주세요.")
            appendLine()
            appendLine("## 💡 오늘의 배움 (Learnings)")
            appendLine()
            appendLine("- 실수했거나 새로 알게 된 점을 적어주세요.")
            appendLine()
            appendLine("## 제출한 코드")
            appendLine()
            appendLine("```$markdownLanguage")
            append(code)
            appendLine()
            appendLine("```")
            appendLine()
            appendLine("## 에러 로그")
            appendLine()
            appendLine("```text")
            appendLine(errorMessage)
            appendLine("```")
            appendLine()
            appendLine("---")
            appendLine("Generated by DidimLog")
        }
    }

    /**
     * 상세한 성공 회고 템플릿을 생성한다.
     */
    fun generateDetailSuccess(title: String, keywords: String, markdownLanguage: String, code: String, solveTime: String?): String {
        return buildString {
            appendLine("# 🏆 $title 해결 회고")
            appendLine()
            if (solveTime != null && solveTime.isNotBlank()) {
                appendLine("⏱️ **풀이 소요 시간:** $solveTime")
                appendLine()
            }
            appendLine("## 🔑 학습 키워드")
            appendLine()
            appendLine(keywords)
            appendLine()
            appendLine("## 1. 접근 방법 (Approach)")
            appendLine()
            appendLine("- 문제를 해결하기 위해 어떤 알고리즘이나 자료구조를 선택했나요?")
            appendLine("- 풀이의 핵심 로직을 한 줄로 요약해 보세요.")
            appendLine()
            appendLine("## 2. 복잡도 분석 (Complexity)")
            appendLine()
            appendLine("- 시간 복잡도: O(?)")
            appendLine("- 공간 복잡도: O(?)")
            appendLine()
            appendLine("## 3. 리팩토링 포인트 (Refactoring)")
            appendLine()
            appendLine("- 개선할 수 있는 변수/함수명, 중복 제거, 로직 단순화 포인트를 적어보세요.")
            appendLine()
            appendLine("## 4. 다른 풀이와 비교 (Comparison)")
            appendLine()
            appendLine("- 다른 사람의 풀이(또는 표준 풀이)와 비교해서 내 풀이의 장단점을 정리해보세요.")
            appendLine()
            appendLine("## 5. 다음 액션 (Next)")
            appendLine()
            appendLine("- 다음에 같은 유형을 만나면 어떤 점을 더 잘할지 한 줄로 적어보세요.")
            appendLine()
            appendLine("## 제출한 코드")
            appendLine()
            appendLine("```$markdownLanguage")
            append(code)
            appendLine()
            appendLine("```")
            appendLine()
            appendLine("---")
            appendLine("Generated by DidimLog")
        }
    }

    /**
     * 상세한 실패 회고 템플릿을 생성한다.
     */
    fun generateDetailFailure(title: String, keywords: String, markdownLanguage: String, code: String, errorMessage: String, solveTime: String?): String {
        return buildString {
            appendLine("# 💥 $title 오답 노트")
            appendLine()
            if (solveTime != null && solveTime.isNotBlank()) {
                appendLine("⏱️ **풀이 소요 시간:** $solveTime")
                appendLine()
            }
            appendLine("## 🔑 학습 키워드")
            appendLine()
            appendLine(keywords)
            appendLine()
            appendLine("## 1. 실패 현상 (Symptom)")
            appendLine()
            appendLine("- 어떤 종류의 에러가 발생했나요? (시간 초과, 메모리 초과, 틀렸습니다, 런타임 에러)")
            appendLine("- 테스트 케이스 중 통과하지 못한 예시가 있나요?")
            appendLine()
            appendLine("## 2. 나의 접근 (My Attempt)")
            appendLine()
            appendLine("- 어떤 로직으로 풀려고 시도했나요?")
            appendLine()
            appendLine("## 3. 원인 추정 (Root Cause)")
            appendLine()
            appendLine("- 왜 실패했다고 생각하나요? (논리/구현/복잡도/입출력 등)")
            appendLine()
            appendLine("## 4. 반례/재현 케이스 (Counter Example)")
            appendLine()
            appendLine("- 내 코드를 깨뜨리는 입력을 적어보세요.")
            appendLine()
            appendLine("## 5. 다음 시도 계획 (Next)")
            appendLine()
            appendLine("- 다음 시도에서 바꿀 점을 체크리스트로 적어보세요.")
            appendLine()
            appendLine("## 제출한 코드")
            appendLine()
            appendLine("```$markdownLanguage")
            append(code)
            appendLine()
            appendLine("```")
            appendLine()
            appendLine("## 에러 로그")
            appendLine()
            appendLine("```text")
            appendLine(errorMessage)
            appendLine("```")
            appendLine()
            appendLine("---")
            appendLine("Generated by DidimLog")
        }
    }
}
