package com.didimlog.application.template

import com.didimlog.domain.enums.TemplateOwnershipType
import com.didimlog.domain.repository.TemplateRepository
import com.didimlog.domain.template.Template
import jakarta.annotation.PostConstruct
import org.springframework.stereotype.Component

/**
 * 시스템 템플릿 초기화 컴포넌트
 * 애플리케이션 시작 시 시스템 템플릿을 생성한다.
 */
@Component
class TemplateInitializer(
    private val templateRepository: TemplateRepository
) {

    @PostConstruct
    fun initializeSystemTemplates() {
        initializeSimpleTemplate()
        initializeDetailTemplate()
    }

    /**
     * 요약(Simple) 시스템 템플릿을 초기화한다.
     */
    private fun initializeSimpleTemplate() {
        val existingTemplate = templateRepository.findByType(TemplateOwnershipType.SYSTEM)
            .firstOrNull { it.title == "Simple(요약)" }
        
        if (existingTemplate != null) {
            return
        }

        val simpleContent = """
# 🏆 {{problemTitle}}

## 🔑 핵심 로직 (Key Logic)

- 풀이의 핵심 공식이나 접근법을 한 줄로 적어주세요.

## 💡 오늘의 배움 (Learnings)

- 실수했거나 새로 알게 된 점을 적어주세요.

## 제출한 코드

```{{language}}
여기에 코드를 작성하세요.
```

---
[문제 링크]({{link}})
Generated by DidimLog
        """.trimIndent()

        val simpleTemplate = Template(
            studentId = null,
            title = "Simple(요약)",
            content = simpleContent,
            type = TemplateOwnershipType.SYSTEM,
            isDefault = false
        )

        templateRepository.save(simpleTemplate)
    }

    /**
     * 상세(Detail) 시스템 템플릿을 초기화한다.
     */
    private fun initializeDetailTemplate() {
        val existingTemplate = templateRepository.findByType(TemplateOwnershipType.SYSTEM)
            .firstOrNull { it.title == "Detail(상세)" }
        
        if (existingTemplate != null) {
            return
        }

        val detailContent = """
# 🏆 {{problemTitle}} 해결 회고

## 1. 접근 방법 (Approach)

- 문제를 해결하기 위해 어떤 알고리즘이나 자료구조를 선택했나요?
- 풀이의 핵심 로직을 한 줄로 요약해 보세요.

## 2. 복잡도 분석 (Complexity)

- 시간 복잡도: O(?)
- 공간 복잡도: O(?)

## 3. 리팩토링 포인트 (Refactoring)

- 개선할 수 있는 변수/함수명, 중복 제거, 로직 단순화 포인트를 적어보세요.

## 4. 다른 풀이와 비교 (Comparison)

- 다른 사람의 풀이(또는 표준 풀이)와 비교해서 내 풀이의 장단점을 정리해보세요.

## 5. 다음 액션 (Next)

- 다음에 같은 유형을 만나면 어떤 점을 더 잘할지 한 줄로 적어보세요.

## 제출한 코드

```{{language}}
여기에 코드를 작성하세요.
```

---
[문제 링크]({{link}}) | 티어: {{tier}}
Generated by DidimLog
        """.trimIndent()

        val detailTemplate = Template(
            studentId = null,
            title = "Detail(상세)",
            content = detailContent,
            type = TemplateOwnershipType.SYSTEM,
            isDefault = false
        )

        templateRepository.save(detailTemplate)
    }
}
