package com.didimlog.domain.enums

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

@DisplayName("ProblemCategory Enum 테스트")
class ProblemCategoryTest {

    @Test
    @DisplayName("fromKorean은 한글 태그를 올바른 ProblemCategory로 변환한다")
    fun `한글 태그를 ProblemCategory로 변환`() {
        // then
        assertThat(ProblemCategory.fromKorean("수학")).isEqualTo(ProblemCategory.MATHEMATICS)
        assertThat(ProblemCategory.fromKorean("구현")).isEqualTo(ProblemCategory.IMPLEMENTATION)
        assertThat(ProblemCategory.fromKorean("다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DP)
        assertThat(ProblemCategory.fromKorean("자료 구조")).isEqualTo(ProblemCategory.DATA_STRUCTURES)
        assertThat(ProblemCategory.fromKorean("그래프 이론")).isEqualTo(ProblemCategory.GRAPH_THEORY)
        assertThat(ProblemCategory.fromKorean("그리디 알고리즘")).isEqualTo(ProblemCategory.GREEDY)
        assertThat(ProblemCategory.fromKorean("문자열")).isEqualTo(ProblemCategory.STRING)
        assertThat(ProblemCategory.fromKorean("브루트포스 알고리즘")).isEqualTo(ProblemCategory.BRUTEFORCE)
        assertThat(ProblemCategory.fromKorean("그래프 탐색")).isEqualTo(ProblemCategory.GRAPH_TRAVERSAL)
        assertThat(ProblemCategory.fromKorean("정렬")).isEqualTo(ProblemCategory.SORTING)
        assertThat(ProblemCategory.fromKorean("기하학")).isEqualTo(ProblemCategory.GEOMETRY)
        assertThat(ProblemCategory.fromKorean("트리")).isEqualTo(ProblemCategory.TREE)
        assertThat(ProblemCategory.fromKorean("정수론")).isEqualTo(ProblemCategory.NUMBER_THEORY)
        assertThat(ProblemCategory.fromKorean("이분 탐색")).isEqualTo(ProblemCategory.BINARY_SEARCH)
        assertThat(ProblemCategory.fromKorean("너비 우선 탐색")).isEqualTo(ProblemCategory.BFS)
        assertThat(ProblemCategory.fromKorean("깊이 우선 탐색")).isEqualTo(ProblemCategory.DFS)
        assertThat(ProblemCategory.fromKorean("데이크스트라")).isEqualTo(ProblemCategory.DIJKSTRA)
        assertThat(ProblemCategory.fromKorean("비트마스킹")).isEqualTo(ProblemCategory.BITMASK)
        assertThat(ProblemCategory.fromKorean("백트래킹")).isEqualTo(ProblemCategory.BACKTRACKING)
        assertThat(ProblemCategory.fromKorean("시뮬레이션")).isEqualTo(ProblemCategory.SIMULATION)
        assertThat(ProblemCategory.fromKorean("누적 합")).isEqualTo(ProblemCategory.PREFIX_SUM)
        assertThat(ProblemCategory.fromKorean("두 포인터")).isEqualTo(ProblemCategory.TWO_POINTER)
    }

    @Test
    @DisplayName("fromKorean은 공백이 포함된 한글 태그도 올바르게 변환한다 (공백 제거 후 비교)")
    fun `공백 포함 한글 태그 변환`() {
        // then
        assertThat(ProblemCategory.fromKorean("  수학  ")).isEqualTo(ProblemCategory.MATHEMATICS)
        assertThat(ProblemCategory.fromKorean(" 다이나믹 프로그래밍 ")).isEqualTo(ProblemCategory.DP)
        assertThat(ProblemCategory.fromKorean("애드 혹")).isEqualTo(ProblemCategory.AD_HOC)
        assertThat(ProblemCategory.fromKorean("애드혹")).isEqualTo(ProblemCategory.AD_HOC) // 공백 제거 후 매칭
    }

    @Test
    @DisplayName("fromKorean은 매칭되지 않는 태그에 대해 UNKNOWN을 반환한다")
    fun `매칭 안 되는 태그는 UNKNOWN 반환`() {
        // then
        assertThat(ProblemCategory.fromKorean("알 수 없는 태그")).isEqualTo(ProblemCategory.UNKNOWN)
        assertThat(ProblemCategory.fromKorean("존재하지 않는 카테고리")).isEqualTo(ProblemCategory.UNKNOWN)
        assertThat(ProblemCategory.fromKorean("")).isEqualTo(ProblemCategory.UNKNOWN)
    }

    @Test
    @DisplayName("fromKorean은 대소문자를 무시하고 매칭한다")
    fun `대소문자 무시 매칭`() {
        // then: 대소문자 무시 (한글에는 영향 없지만, 영문 태그가 있을 경우를 대비)
        assertThat(ProblemCategory.fromKorean("수학")).isEqualTo(ProblemCategory.MATHEMATICS)
        assertThat(ProblemCategory.fromKorean("구현")).isEqualTo(ProblemCategory.IMPLEMENTATION)
    }

    @Test
    @DisplayName("각 ProblemCategory의 englishName이 올바르게 설정되어 있다")
    fun `englishName 값 검증`() {
        // then
        assertThat(ProblemCategory.MATHEMATICS.englishName).isEqualTo("Mathematics")
        assertThat(ProblemCategory.IMPLEMENTATION.englishName).isEqualTo("Implementation")
        assertThat(ProblemCategory.DP.englishName).isEqualTo("Dynamic Programming")
        assertThat(ProblemCategory.DATA_STRUCTURES.englishName).isEqualTo("Data Structures")
        assertThat(ProblemCategory.GRAPH_THEORY.englishName).isEqualTo("Graph Theory")
        assertThat(ProblemCategory.GREEDY.englishName).isEqualTo("Greedy")
        assertThat(ProblemCategory.STRING.englishName).isEqualTo("String")
        assertThat(ProblemCategory.BRUTEFORCE.englishName).isEqualTo("Bruteforcing")
        assertThat(ProblemCategory.GRAPH_TRAVERSAL.englishName).isEqualTo("Graph Traversal")
        assertThat(ProblemCategory.SORTING.englishName).isEqualTo("Sorting")
        assertThat(ProblemCategory.GEOMETRY.englishName).isEqualTo("Geometry")
        assertThat(ProblemCategory.TREE.englishName).isEqualTo("Tree")
        assertThat(ProblemCategory.NUMBER_THEORY.englishName).isEqualTo("Number Theory")
        assertThat(ProblemCategory.BINARY_SEARCH.englishName).isEqualTo("Binary Search")
        assertThat(ProblemCategory.BFS.englishName).isEqualTo("Breadth-first Search")
        assertThat(ProblemCategory.DFS.englishName).isEqualTo("Depth-first Search")
        assertThat(ProblemCategory.DIJKSTRA.englishName).isEqualTo("Dijkstra's")
        assertThat(ProblemCategory.BITMASK.englishName).isEqualTo("Bitmask")
        assertThat(ProblemCategory.BACKTRACKING.englishName).isEqualTo("Backtracking")
        assertThat(ProblemCategory.SIMULATION.englishName).isEqualTo("Simulation")
        assertThat(ProblemCategory.PREFIX_SUM.englishName).isEqualTo("Prefix Sum")
        assertThat(ProblemCategory.TWO_POINTER.englishName).isEqualTo("Two-pointer")
        assertThat(ProblemCategory.UNKNOWN.englishName).isEqualTo("Unknown")
    }

    @Test
    @DisplayName("새로 추가된 주요 카테고리들이 올바르게 매핑된다")
    fun `새로 추가된 카테고리 매핑 검증`() {
        // then
        assertThat(ProblemCategory.fromKorean("애드 혹")).isEqualTo(ProblemCategory.AD_HOC)
        assertThat(ProblemCategory.fromKorean("세그먼트 트리")).isEqualTo(ProblemCategory.SEGMENT_TREE)
        assertThat(ProblemCategory.fromKorean("해 구성하기")).isEqualTo(ProblemCategory.CONSTRUCTIVE)
        assertThat(ProblemCategory.fromKorean("사칙연산")).isEqualTo(ProblemCategory.ARITHMETIC)
        assertThat(ProblemCategory.fromKorean("조합론")).isEqualTo(ProblemCategory.COMBINATORICS)
        assertThat(ProblemCategory.fromKorean("많은 조건 분기")).isEqualTo(ProblemCategory.CASE_WORK)
        assertThat(ProblemCategory.fromKorean("집합과 맵")).isEqualTo(ProblemCategory.SET_MAP)
        assertThat(ProblemCategory.fromKorean("최단 경로")).isEqualTo(ProblemCategory.SHORTEST_PATH)
        assertThat(ProblemCategory.fromKorean("해시를 사용한 집합과 맵")).isEqualTo(ProblemCategory.SET_MAP_HASHING)
        assertThat(ProblemCategory.fromKorean("스위핑")).isEqualTo(ProblemCategory.SWEEPING)
        assertThat(ProblemCategory.fromKorean("분리 집합")).isEqualTo(ProblemCategory.DISJOINT_SET)
        assertThat(ProblemCategory.fromKorean("트리에서의 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DP_ON_TREES)
        assertThat(ProblemCategory.fromKorean("트리를 사용한 집합과 맵")).isEqualTo(ProblemCategory.SET_MAP_TREES)
        assertThat(ProblemCategory.fromKorean("파싱")).isEqualTo(ProblemCategory.PARSING)
        assertThat(ProblemCategory.fromKorean("우선순위 큐")).isEqualTo(ProblemCategory.PRIORITY_QUEUE)
        assertThat(ProblemCategory.fromKorean("게임 이론")).isEqualTo(ProblemCategory.GAME_THEORY)
        assertThat(ProblemCategory.fromKorean("매개 변수 탐색")).isEqualTo(ProblemCategory.PARAMETRIC_SEARCH)
        assertThat(ProblemCategory.fromKorean("분할 정복")).isEqualTo(ProblemCategory.DIVIDE_AND_CONQUER)
        assertThat(ProblemCategory.fromKorean("스택")).isEqualTo(ProblemCategory.STACK)
        assertThat(ProblemCategory.fromKorean("확률론")).isEqualTo(ProblemCategory.PROBABILITY)
        assertThat(ProblemCategory.fromKorean("소수 판정")).isEqualTo(ProblemCategory.PRIMALITY_TEST)
        assertThat(ProblemCategory.fromKorean("느리게 갱신되는 세그먼트 트리")).isEqualTo(ProblemCategory.SEGMENT_TREE_LAZY)
        assertThat(ProblemCategory.fromKorean("최대 유량")).isEqualTo(ProblemCategory.MAX_FLOW)
        assertThat(ProblemCategory.fromKorean("비트필드를 이용한 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DP_BITFIELD)
        assertThat(ProblemCategory.fromKorean("오프라인 쿼리")).isEqualTo(ProblemCategory.OFFLINE_QUERIES)
        assertThat(ProblemCategory.fromKorean("분할 정복을 이용한 거듭제곱")).isEqualTo(ProblemCategory.EXPONENTIATION_BY_SQUARING)
        assertThat(ProblemCategory.fromKorean("배낭 문제")).isEqualTo(ProblemCategory.KNAPSACK)
        assertThat(ProblemCategory.fromKorean("값 / 좌표 압축")).isEqualTo(ProblemCategory.COORD_COMPRESSION)
        assertThat(ProblemCategory.fromKorean("재귀")).isEqualTo(ProblemCategory.RECURSION)
        assertThat(ProblemCategory.fromKorean("임의 정밀도 / 큰 수 연산")).isEqualTo(ProblemCategory.ARBITRARY_PRECISION)
        assertThat(ProblemCategory.fromKorean("방향 비순환 그래프")).isEqualTo(ProblemCategory.DAG)
        assertThat(ProblemCategory.fromKorean("유클리드 호제법")).isEqualTo(ProblemCategory.EUCLIDEAN)
        assertThat(ProblemCategory.fromKorean("최소 스패닝 트리")).isEqualTo(ProblemCategory.MST)
        assertThat(ProblemCategory.fromKorean("볼록 껍질")).isEqualTo(ProblemCategory.CONVEX_HULL)
        assertThat(ProblemCategory.fromKorean("런타임 전의 전처리")).isEqualTo(ProblemCategory.PRECOMPUTATION)
        assertThat(ProblemCategory.fromKorean("위상 정렬")).isEqualTo(ProblemCategory.TOPOLOGICAL_SORTING)
        assertThat(ProblemCategory.fromKorean("에라토스테네스의 체")).isEqualTo(ProblemCategory.SIEVE)
        assertThat(ProblemCategory.fromKorean("선형대수학")).isEqualTo(ProblemCategory.LINEAR_ALGEBRA)
        assertThat(ProblemCategory.fromKorean("이분 매칭")).isEqualTo(ProblemCategory.BIPARTITE_MATCHING)
        assertThat(ProblemCategory.fromKorean("포함 배제의 원리")).isEqualTo(ProblemCategory.INCLUSION_EXCLUSION)
        assertThat(ProblemCategory.fromKorean("최소 공통 조상")).isEqualTo(ProblemCategory.LCA)
        assertThat(ProblemCategory.fromKorean("희소 배열")).isEqualTo(ProblemCategory.SPARSE_TABLE)
        assertThat(ProblemCategory.fromKorean("격자 그래프")).isEqualTo(ProblemCategory.GRID_GRAPH)
        assertThat(ProblemCategory.fromKorean("해싱")).isEqualTo(ProblemCategory.HASHING)
        assertThat(ProblemCategory.fromKorean("무작위화")).isEqualTo(ProblemCategory.RANDOMIZATION)
        assertThat(ProblemCategory.fromKorean("플로이드–워셜")).isEqualTo(ProblemCategory.FLOYD_WARSHALL)
        assertThat(ProblemCategory.fromKorean("모듈로 곱셈 역원")).isEqualTo(ProblemCategory.MODULAR_INVERSE)
        assertThat(ProblemCategory.fromKorean("강한 연결 요소")).isEqualTo(ProblemCategory.SCC)
        assertThat(ProblemCategory.fromKorean("작은 집합에서 큰 집합으로 합치는 테크닉")).isEqualTo(ProblemCategory.SMALLER_TO_LARGER)
        assertThat(ProblemCategory.fromKorean("선분 교차 판정")).isEqualTo(ProblemCategory.LINE_INTERSECTION)
        assertThat(ProblemCategory.fromKorean("역추적")).isEqualTo(ProblemCategory.TRACEBACK)
        assertThat(ProblemCategory.fromKorean("고속 푸리에 변환")).isEqualTo(ProblemCategory.FFT)
        assertThat(ProblemCategory.fromKorean("미적분학")).isEqualTo(ProblemCategory.CALCULUS)
        assertThat(ProblemCategory.fromKorean("홀짝성")).isEqualTo(ProblemCategory.PARITY)
        assertThat(ProblemCategory.fromKorean("트라이")).isEqualTo(ProblemCategory.TRIE)
        assertThat(ProblemCategory.fromKorean("제곱근 분할법")).isEqualTo(ProblemCategory.SQRT_DECOMPOSITION)
        assertThat(ProblemCategory.fromKorean("덱")).isEqualTo(ProblemCategory.DEQUE)
        assertThat(ProblemCategory.fromKorean("삼분 탐색")).isEqualTo(ProblemCategory.TERNARY_SEARCH)
        assertThat(ProblemCategory.fromKorean("3차원 기하학")).isEqualTo(ProblemCategory.GEOMETRY_3D)
        assertThat(ProblemCategory.fromKorean("휴리스틱")).isEqualTo(ProblemCategory.HEURISTICS)
        assertThat(ProblemCategory.fromKorean("접미사 배열과 lcp 배열")).isEqualTo(ProblemCategory.SUFFIX_ARRAY)
        assertThat(ProblemCategory.fromKorean("오일러 경로 테크닉")).isEqualTo(ProblemCategory.EULER_TOUR)
        assertThat(ProblemCategory.fromKorean("스프라그–그런디 정리")).isEqualTo(ProblemCategory.SPRAGUE_GRUNDY)
        assertThat(ProblemCategory.fromKorean("최소 비용 최대 유량")).isEqualTo(ProblemCategory.MCMF)
        assertThat(ProblemCategory.fromKorean("슬라이딩 윈도우")).isEqualTo(ProblemCategory.SLIDING_WINDOW)
        assertThat(ProblemCategory.fromKorean("볼록 껍질을 이용한 최적화")).isEqualTo(ProblemCategory.CONVEX_HULL_TRICK)
        assertThat(ProblemCategory.fromKorean("센트로이드")).isEqualTo(ProblemCategory.CENTROID)
        assertThat(ProblemCategory.fromKorean("중간에서 만나기")).isEqualTo(ProblemCategory.MEET_IN_THE_MIDDLE)
        assertThat(ProblemCategory.fromKorean("피타고라스 정리")).isEqualTo(ProblemCategory.PYTHAGORAS)
        assertThat(ProblemCategory.fromKorean("순열 사이클 분할")).isEqualTo(ProblemCategory.PERMUTATION_CYCLE)
        assertThat(ProblemCategory.fromKorean("비트 집합")).isEqualTo(ProblemCategory.BIT_SET)
        assertThat(ProblemCategory.fromKorean("가장 긴 증가하는 부분 수열 문제")).isEqualTo(ProblemCategory.LIS)
        assertThat(ProblemCategory.fromKorean("kmp")).isEqualTo(ProblemCategory.KMP)
        assertThat(ProblemCategory.fromKorean("소인수분해")).isEqualTo(ProblemCategory.PRIME_FACTORIZATION)
        assertThat(ProblemCategory.fromKorean("가우스 소거법")).isEqualTo(ProblemCategory.GAUSSIAN_ELIMINATION)
        assertThat(ProblemCategory.fromKorean("heavy-light 분할")).isEqualTo(ProblemCategory.HLD)
        assertThat(ProblemCategory.fromKorean("기댓값의 선형성")).isEqualTo(ProblemCategory.LINEARITY_OF_EXPECTATION)
        assertThat(ProblemCategory.fromKorean("이분 그래프")).isEqualTo(ProblemCategory.BIPARTITE_GRAPH)
        assertThat(ProblemCategory.fromKorean("다각형의 넓이")).isEqualTo(ProblemCategory.POLYGON_AREA)
        assertThat(ProblemCategory.fromKorean("최대 유량 최소 컷 정리")).isEqualTo(ProblemCategory.MAX_FLOW_MIN_CUT)
        assertThat(ProblemCategory.fromKorean("센트로이드 분할")).isEqualTo(ProblemCategory.CENTROID_DECOMPOSITION)
        assertThat(ProblemCategory.fromKorean("차분 배열 트릭")).isEqualTo(ProblemCategory.DIFFERENCE_ARRAY)
        assertThat(ProblemCategory.fromKorean("물리학")).isEqualTo(ProblemCategory.PHYSICS)
        assertThat(ProblemCategory.fromKorean("0-1 너비 우선 탐색")).isEqualTo(ProblemCategory.ZERO_ONE_BFS)
        assertThat(ProblemCategory.fromKorean("페르마의 소정리")).isEqualTo(ProblemCategory.FERMAT_LITTLE)
        assertThat(ProblemCategory.fromKorean("오일러 경로")).isEqualTo(ProblemCategory.EULERIAN_PATH)
        assertThat(ProblemCategory.fromKorean("플러드 필")).isEqualTo(ProblemCategory.FLOOD_FILL)
        assertThat(ProblemCategory.fromKorean("2-sat")).isEqualTo(ProblemCategory.TWO_SAT)
        assertThat(ProblemCategory.fromKorean("단절점과 단절선")).isEqualTo(ProblemCategory.ARTICULATION_POINTS)
        assertThat(ProblemCategory.fromKorean("큐")).isEqualTo(ProblemCategory.QUEUE)
        assertThat(ProblemCategory.fromKorean("외판원 순회 문제")).isEqualTo(ProblemCategory.TSP)
        assertThat(ProblemCategory.fromKorean("비둘기집 원리")).isEqualTo(ProblemCategory.PIGEONHOLE)
        assertThat(ProblemCategory.fromKorean("퍼시스턴트 세그먼트 트리")).isEqualTo(ProblemCategory.PERSISTENT_SEGMENT_TREE)
        assertThat(ProblemCategory.fromKorean("함수형 그래프")).isEqualTo(ProblemCategory.FUNCTIONAL_GRAPH)
        assertThat(ProblemCategory.fromKorean("평면 그래프")).isEqualTo(ProblemCategory.PLANAR_GRAPH)
        assertThat(ProblemCategory.fromKorean("오일러 피 함수")).isEqualTo(ProblemCategory.EULER_TOTIENT)
        assertThat(ProblemCategory.fromKorean("덱을 이용한 구간 최댓값 트릭")).isEqualTo(ProblemCategory.DEQUE_RANGE_MAX)
        assertThat(ProblemCategory.fromKorean("이중 연결 요소")).isEqualTo(ProblemCategory.BICONNECTED_COMPONENT)
        assertThat(ProblemCategory.fromKorean("볼록 다각형 내부의 점 판정")).isEqualTo(ProblemCategory.POINT_IN_CONVEX_POLYGON)
        assertThat(ProblemCategory.fromKorean("연결 리스트")).isEqualTo(ProblemCategory.LINKED_LIST)
        assertThat(ProblemCategory.fromKorean("중국인의 나머지 정리")).isEqualTo(ProblemCategory.CRT)
        assertThat(ProblemCategory.fromKorean("자릿수를 이용한 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DIGIT_DP)
        assertThat(ProblemCategory.fromKorean("생성 함수")).isEqualTo(ProblemCategory.GENERATING_FUNCTION)
        assertThat(ProblemCategory.fromKorean("각도 정렬")).isEqualTo(ProblemCategory.ANGLE_SORTING)
        assertThat(ProblemCategory.fromKorean("선인장")).isEqualTo(ProblemCategory.CACTUS)
        assertThat(ProblemCategory.fromKorean("트리에서의 전방향 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.REROOTING)
        assertThat(ProblemCategory.fromKorean("확장 유클리드 호제법")).isEqualTo(ProblemCategory.EXTENDED_EUCLIDEAN)
        assertThat(ProblemCategory.fromKorean("mo's")).isEqualTo(ProblemCategory.MOS)
        assertThat(ProblemCategory.fromKorean("벨만–포드")).isEqualTo(ProblemCategory.BELLMAN_FORD)
        assertThat(ProblemCategory.fromKorean("트리의 지름")).isEqualTo(ProblemCategory.TREE_DIAMETER)
        assertThat(ProblemCategory.fromKorean("스플레이 트리")).isEqualTo(ProblemCategory.SPLAY_TREE)
        assertThat(ProblemCategory.fromKorean("분할 정복을 사용한 최적화")).isEqualTo(ProblemCategory.DIVIDE_CONQUER_OPT)
        assertThat(ProblemCategory.fromKorean("병렬 이분 탐색")).isEqualTo(ProblemCategory.PARALLEL_BINARY_SEARCH)
        assertThat(ProblemCategory.fromKorean("불변량 찾기")).isEqualTo(ProblemCategory.FINDING_INVARIANTS)
        assertThat(ProblemCategory.fromKorean("최대 부분 배열 문제")).isEqualTo(ProblemCategory.MAX_SUBARRAY)
        assertThat(ProblemCategory.fromKorean("조화수")).isEqualTo(ProblemCategory.HARMONIC_NUMBER)
        assertThat(ProblemCategory.fromKorean("반평면 교집합")).isEqualTo(ProblemCategory.HALF_PLANE_INTERSECTION)
        assertThat(ProblemCategory.fromKorean("회전하는 캘리퍼스")).isEqualTo(ProblemCategory.ROTATING_CALIPERS)
        assertThat(ProblemCategory.fromKorean("오일러 지표 (χ=v-e+f)")).isEqualTo(ProblemCategory.EULER_CHARACTERISTIC)
        assertThat(ProblemCategory.fromKorean("정규 표현식")).isEqualTo(ProblemCategory.REGEX)
        assertThat(ProblemCategory.fromKorean("함수 개형을 이용한 최적화")).isEqualTo(ProblemCategory.SLOPE_TRICK)
        assertThat(ProblemCategory.fromKorean("다차원 세그먼트 트리")).isEqualTo(ProblemCategory.MULTIDIMENSIONAL_SEGMENT_TREE)
        assertThat(ProblemCategory.fromKorean("부분집합의 합 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.SOS_DP)
        assertThat(ProblemCategory.fromKorean("아호-코라식")).isEqualTo(ProblemCategory.AHO_CORASICK)
        assertThat(ProblemCategory.fromKorean("덱을 이용한 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DP_DEQUE)
        assertThat(ProblemCategory.fromKorean("매내처")).isEqualTo(ProblemCategory.MANACHER)
        assertThat(ProblemCategory.fromKorean("밀러–라빈 소수 판별법")).isEqualTo(ProblemCategory.MILLER_RABIN)
        assertThat(ProblemCategory.fromKorean("폴라드 로")).isEqualTo(ProblemCategory.POLLARD_RHO)
        assertThat(ProblemCategory.fromKorean("뫼비우스 반전 공식")).isEqualTo(ProblemCategory.MOBIUS_INVERSION)
        assertThat(ProblemCategory.fromKorean("트리 동형 사상")).isEqualTo(ProblemCategory.TREE_ISOMORPHISM)
        assertThat(ProblemCategory.fromKorean("머지 소트 트리")).isEqualTo(ProblemCategory.MERGE_SORT_TREE)
        assertThat(ProblemCategory.fromKorean("수치해석")).isEqualTo(ProblemCategory.NUMERICAL_ANALYSIS)
        assertThat(ProblemCategory.fromKorean("최장 공통 부분 수열 문제")).isEqualTo(ProblemCategory.LCS)
        assertThat(ProblemCategory.fromKorean("오목 다각형 내부의 점 판정")).isEqualTo(ProblemCategory.POINT_IN_NON_CONVEX)
        assertThat(ProblemCategory.fromKorean("커넥션 프로파일을 이용한 다이나믹 프로그래밍")).isEqualTo(ProblemCategory.DP_CONNECTION_PROFILE)
        assertThat(ProblemCategory.fromKorean("라빈–카프")).isEqualTo(ProblemCategory.RABIN_KARP)
        assertThat(ProblemCategory.fromKorean("담금질 기법")).isEqualTo(ProblemCategory.SIMULATED_ANNEALING)
        assertThat(ProblemCategory.fromKorean("홀의 결혼 정리")).isEqualTo(ProblemCategory.HALLS_THEOREM)
        assertThat(ProblemCategory.fromKorean("링크/컷 트리")).isEqualTo(ProblemCategory.LINK_CUT_TREE)
        assertThat(ProblemCategory.fromKorean("벌리캠프–매시")).isEqualTo(ProblemCategory.BERLEKAMP_MASSEY)
        assertThat(ProblemCategory.fromKorean("통계학")).isEqualTo(ProblemCategory.STATISTICS)
        assertThat(ProblemCategory.fromKorean("데카르트 트리")).isEqualTo(ProblemCategory.CARTESIAN_TREE)
        assertThat(ProblemCategory.fromKorean("오프라인 동적 연결성 판정")).isEqualTo(ProblemCategory.OFFLINE_DYNAMIC_CONNECTIVITY)
        assertThat(ProblemCategory.fromKorean("헝가리안")).isEqualTo(ProblemCategory.HUNGARIAN)
        assertThat(ProblemCategory.fromKorean("z")).isEqualTo(ProblemCategory.Z)
        assertThat(ProblemCategory.fromKorean("aliens 트릭")).isEqualTo(ProblemCategory.ALIENS)
        assertThat(ProblemCategory.fromKorean("트리 압축")).isEqualTo(ProblemCategory.TREE_COMPRESSION)
        assertThat(ProblemCategory.fromKorean("도형에서의 불 연산")).isEqualTo(ProblemCategory.BOOLEAN_OPERATIONS)
        assertThat(ProblemCategory.fromKorean("선형 계획법")).isEqualTo(ProblemCategory.LINEAR_PROGRAMMING)
        assertThat(ProblemCategory.fromKorean("리–차오 트리")).isEqualTo(ProblemCategory.LI_CHAO_TREE)
        assertThat(ProblemCategory.fromKorean("보로노이 다이어그램")).isEqualTo(ProblemCategory.VORONOI)
        assertThat(ProblemCategory.fromKorean("뤼카 정리")).isEqualTo(ProblemCategory.LUCAS)
        assertThat(ProblemCategory.fromKorean("배타적 논리합 기저 (gf(2))")).isEqualTo(ProblemCategory.XOR_BASIS)
        assertThat(ProblemCategory.fromKorean("쌍대 그래프")).isEqualTo(ProblemCategory.DUAL_GRAPH)
        assertThat(ProblemCategory.fromKorean("그린 정리")).isEqualTo(ProblemCategory.GREEN)
        assertThat(ProblemCategory.fromKorean("서큘레이션")).isEqualTo(ProblemCategory.CIRCULATION)
        assertThat(ProblemCategory.fromKorean("쌍대성")).isEqualTo(ProblemCategory.DUALITY)
        assertThat(ProblemCategory.fromKorean("세그먼트 트리 비츠")).isEqualTo(ProblemCategory.SEGMENT_TREE_BEATS)
        assertThat(ProblemCategory.fromKorean("다항식 보간법")).isEqualTo(ProblemCategory.POLYNOMIAL_INTERPOLATION)
        assertThat(ProblemCategory.fromKorean("일반적인 매칭")).isEqualTo(ProblemCategory.GENERAL_MATCHING)
        assertThat(ProblemCategory.fromKorean("단조 큐를 이용한 최적화")).isEqualTo(ProblemCategory.MONOTONE_QUEUE_OPT)
        assertThat(ProblemCategory.fromKorean("매트로이드")).isEqualTo(ProblemCategory.MATROID)
        assertThat(ProblemCategory.fromKorean("접미사 트리")).isEqualTo(ProblemCategory.SUFFIX_TREE)
        assertThat(ProblemCategory.fromKorean("픽의 정리")).isEqualTo(ProblemCategory.PICKS_THEOREM)
        assertThat(ProblemCategory.fromKorean("다항식을 이용한 선형점화식 계산")).isEqualTo(ProblemCategory.LINEAR_RECURRENCE)
        assertThat(ProblemCategory.fromKorean("4차원 이상의 기하학")).isEqualTo(ProblemCategory.GEOMETRY_HYPER)
        assertThat(ProblemCategory.fromKorean("이산 로그")).isEqualTo(ProblemCategory.DISCRETE_LOG)
        assertThat(ProblemCategory.fromKorean("최소 외접원")).isEqualTo(ProblemCategory.MIN_ENCLOSING_CIRCLE)
        assertThat(ProblemCategory.fromKorean("트리 분할")).isEqualTo(ProblemCategory.TREE_DECOMPOSITION)
        assertThat(ProblemCategory.fromKorean("cdq 분할 정복")).isEqualTo(ProblemCategory.CDQ)
        assertThat(ProblemCategory.fromKorean("번사이드 보조정리")).isEqualTo(ProblemCategory.BURNSIDE)
        assertThat(ProblemCategory.fromKorean("차수열")).isEqualTo(ProblemCategory.DEGREE_SEQUENCE)
        assertThat(ProblemCategory.fromKorean("탑 트리")).isEqualTo(ProblemCategory.TOP_TREE)
        assertThat(ProblemCategory.fromKorean("양방향 탐색")).isEqualTo(ProblemCategory.BIDIRECTIONAL_SEARCH)
        assertThat(ProblemCategory.fromKorean("도미네이터 트리")).isEqualTo(ProblemCategory.DOMINATOR_TREE)
        assertThat(ProblemCategory.fromKorean("차분 공격")).isEqualTo(ProblemCategory.DIFFERENTIAL_CRYPTANALYSIS)
        assertThat(ProblemCategory.fromKorean("utf-8 입력 처리")).isEqualTo(ProblemCategory.UTF8)
        assertThat(ProblemCategory.fromKorean("bulldozer 트릭")).isEqualTo(ProblemCategory.BULLDOZER)
        assertThat(ProblemCategory.fromKorean("회문 트리")).isEqualTo(ProblemCategory.PALINDROME_TREE)
        assertThat(ProblemCategory.fromKorean("춤추는 링크")).isEqualTo(ProblemCategory.DANCING_LINKS)
        assertThat(ProblemCategory.fromKorean("크누스 x")).isEqualTo(ProblemCategory.KNUTH_X)
        assertThat(ProblemCategory.fromKorean("안정 결혼 문제")).isEqualTo(ProblemCategory.STABLE_MARRIAGE)
        assertThat(ProblemCategory.fromKorean("경사 하강법")).isEqualTo(ProblemCategory.GRADIENT_DESCENT)
        assertThat(ProblemCategory.fromKorean("린드스트롬–게셀–비엔노 보조정리")).isEqualTo(ProblemCategory.LGV)
        assertThat(ProblemCategory.fromKorean("피사노 주기")).isEqualTo(ProblemCategory.PISANO)
        assertThat(ProblemCategory.fromKorean("델로네 삼각분할")).isEqualTo(ProblemCategory.DELAUNAY)
        assertThat(ProblemCategory.fromKorean("베이즈 정리")).isEqualTo(ProblemCategory.BAYES)
        assertThat(ProblemCategory.fromKorean("이산 제곱근")).isEqualTo(ProblemCategory.DISCRETE_SQRT)
        assertThat(ProblemCategory.fromKorean("로프")).isEqualTo(ProblemCategory.ROPE)
        assertThat(ProblemCategory.fromKorean("유리 등차수열의 내림 합")).isEqualTo(ProblemCategory.RATIONAL_SUM)
        assertThat(ProblemCategory.fromKorean("크누스 최적화")).isEqualTo(ProblemCategory.KNUTH_OPT)
        assertThat(ProblemCategory.fromKorean("다중 대입값 계산")).isEqualTo(ProblemCategory.MULTIPOINT_EVAL)
        assertThat(ProblemCategory.fromKorean("비트 집합을 이용한 최장 공통 부분 수열 최적화")).isEqualTo(ProblemCategory.LCS_BITSET)
        assertThat(ProblemCategory.fromKorean("히르쉬버그")).isEqualTo(ProblemCategory.HIRSCHBERG)
        assertThat(ProblemCategory.fromKorean("현 그래프")).isEqualTo(ProblemCategory.CHORDAL_GRAPH)
        assertThat(ProblemCategory.fromKorean("생일 문제")).isEqualTo(ProblemCategory.BIRTHDAY)
        assertThat(ProblemCategory.fromKorean("유향 최소 스패닝 트리")).isEqualTo(ProblemCategory.DIRECTED_MST)
        assertThat(ProblemCategory.fromKorean("스토어–바그너")).isEqualTo(ProblemCategory.STOER_WAGNER)
        assertThat(ProblemCategory.fromKorean("지수승강 보조정리")).isEqualTo(ProblemCategory.LTE)
        assertThat(ProblemCategory.fromKorean("다이얼")).isEqualTo(ProblemCategory.DIAL)
        assertThat(ProblemCategory.fromKorean("하켄부시 게임")).isEqualTo(ProblemCategory.HACKENBUSH)
        assertThat(ProblemCategory.fromKorean("키네틱 세그먼트 트리")).isEqualTo(ProblemCategory.KINETIC_SEGMENT_TREE)
        assertThat(ProblemCategory.fromKorean("보이어–무어 다수결 투표")).isEqualTo(ProblemCategory.BOYER_MOORE)
        assertThat(ProblemCategory.fromKorean("레드-블랙 트리")).isEqualTo(ProblemCategory.RED_BLACK_TREE)
    }
}

