package com.didimlog.application.ai

import com.didimlog.infra.ai.PromptTemplateLoader
import com.didimlog.infra.util.HtmlTextExtractor
import org.springframework.stereotype.Component

@Component
class AiPromptFactory(
    private val templateLoader: PromptTemplateLoader
) {

    /**
     * 풀이 성공 여부에 따라 시스템 프롬프트를 생성한다.
     * 성공/실패에 따라 적절한 프롬프트 템플릿 파일을 로드한다.
     *
     * @param isSuccess 풀이 성공 여부
     * @return 시스템 프롬프트 문자열
     */
    fun createSystemPrompt(isSuccess: Boolean): String {
        if (isSuccess) {
            return templateLoader.loadTemplate("success-retrospective.md")
        }
        return templateLoader.loadTemplate("failure-retrospective.md")
    }

    /**
     * 사용자 프롬프트를 생성한다.
     * 문제 정보와 사용자 코드를 포함한 입력 데이터를 마크다운 형식으로 구성한다.
     *
     * @param problemId 문제 ID
     * @param problemTitle 문제 제목
     * @param problemDescription 문제 본문 HTML (nullable)
     * @param code 사용자 코드
     * @param isSuccess 풀이 성공 여부
     * @return 사용자 프롬프트 문자열
     */
    fun createUserPrompt(
        problemId: String,
        problemTitle: String,
        problemDescription: String?,
        code: String,
        isSuccess: Boolean
    ): String {
        val descriptionText = HtmlTextExtractor.extractText(problemDescription) ?: "문제 설명을 불러올 수 없습니다."
        val isSuccessText = when (isSuccess) {
            true -> "true"
            false -> "false"
        }

        return """
        # Input Data
        - 문제 번호: $problemId
        - 문제 제목: $problemTitle
        - 문제 본문(HTML/Text): $descriptionText
        - 풀이 결과: $isSuccessText
        - 사용자 코드:
        $code

        # Instruction
        1. **문제 설명 요약:** 제공된 문제 본문을 읽고, 어떤 문제인지 1~2문장으로 핵심만 요약해라.
        2. **분석:**
           - (성공 시): 효율성(시간/공간 복잡도)과 잘한 점(알고리즘 선택 등)을 칭찬해라.
           - (실패 시): 실패 원인을 분석하고, 정답 대신 학습해야 할 키워드를 제시해라.
        3. **내 코드 포함:** 사용자의 코드를 그대로 마크다운 코드 블록으로 감싸서 출력해라.
        4. **형식 준수:** 아래 [Output Format]을 그대로 따를 것.

        # Output Format
        # [$problemId] $problemTitle

        ## 📝 문제 설명
        (여기에 문제를 1~2문장으로 요약하여 작성)

        ## 💻 나의 풀이
        ```java
        $code
        ```
        *(언어는 코드에 맞춰 적절히 감지)*

        ## 💡 핵심 분석 (Key Analysis)
        (성공/실패 여부에 따른 분석 내용 3~4문장)

        ## 🚀 개선점 및 팁
        (리팩토링 제안이나 학습 힌트를 불렛 포인트로 작성)
        - 
        - 

        ---
        > _Generated by DidimLog_
        """.trimIndent()
    }
}
