package com.didimlog.application.log

import com.didimlog.domain.Log
import com.didimlog.domain.repository.LogRepository
import com.didimlog.domain.valueobject.LogCode
import com.didimlog.domain.valueobject.LogContent
import com.didimlog.domain.valueobject.LogTitle
import io.mockk.every
import io.mockk.mockk
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.time.LocalDateTime
import java.util.Optional

@DisplayName("TemplateService 테스트")
class TemplateServiceTest {

    private val logRepository: LogRepository = mockk()
    private val templateService = TemplateService(logRepository)

    @Test
    @DisplayName("템플릿 생성 시 문자열 맨 끝에 footer가 붙는다")
    fun `footer appended`() {
        val logId = "log-1"
        val createdAt = LocalDateTime.of(2025, 12, 31, 12, 0)
        val log = Log(
            id = logId,
            title = LogTitle("제목"),
            content = LogContent("내용"),
            code = LogCode("print('hi')"),
            createdAt = createdAt
        )
        every { logRepository.findById(logId) } returns Optional.of(log)

        val markdown = templateService.generateTemplate(logId)

        assertThat(markdown).contains("# 제목")
        assertThat(markdown).contains("Date: $createdAt")
        assertThat(markdown).endsWith("---\nGenerated by DidimLog\n")
    }
}


