package com.didimlog.application.log

import com.didimlog.domain.repository.LogRepository
import org.springframework.stereotype.Service

@Service
class TemplateService(
    private val logRepository: LogRepository
) {

    fun generateTemplate(logId: String): String {
        val log = logRepository.findById(logId).orElseThrow { IllegalArgumentException("로그를 찾을 수 없습니다. logId=$logId") }
        return buildString {
            appendLine("# ${log.title.value}")
            appendLine()
            appendLine("- Date: ${log.createdAt}")
            appendLine()
            appendLine(log.content.value)
            appendLine()
            appendLine(FOOTER_SEPARATOR)
            appendLine(FOOTER_TEXT)
        }
    }

    companion object {
        private const val FOOTER_SEPARATOR = "---"
        private const val FOOTER_TEXT = "Generated by DidimLog"
    }
}


