package com.didimlog.domain.enums

/**
 * 알고리즘 문제 카테고리를 나타내는 Enum
 * 한글 태그를 영문 표준명으로 매핑하여 데이터 일관성을 유지한다.
 *
 * @property englishName DB 저장용 영문 표준명
 * @property koreanName 한글 태그 매칭용 이름
 */
enum class ProblemCategory(val englishName: String, val koreanName: String) {
    // === 주요 알고리즘 (Top Tier) ===
    MATHEMATICS("Mathematics", "수학"),
    IMPLEMENTATION("Implementation", "구현"),
    DP("Dynamic Programming", "다이나믹 프로그래밍"),
    DATA_STRUCTURES("Data Structures", "자료 구조"),
    GRAPH_THEORY("Graph Theory", "그래프 이론"),
    GREEDY("Greedy", "그리디 알고리즘"),
    STRING("String", "문자열"),
    BRUTEFORCE("Bruteforcing", "브루트포스 알고리즘"),
    GRAPH_TRAVERSAL("Graph Traversal", "그래프 탐색"),
    SORTING("Sorting", "정렬"),
    AD_HOC("Ad-hoc", "애드 혹"),
    GEOMETRY("Geometry", "기하학"),
    TREE("Tree", "트리"),
    NUMBER_THEORY("Number Theory", "정수론"),
    SEGMENT_TREE("Segment Tree", "세그먼트 트리"),
    BINARY_SEARCH("Binary Search", "이분 탐색"),
    CONSTRUCTIVE("Constructive", "해 구성하기"),
    ARITHMETIC("Arithmetic", "사칙연산"),
    SIMULATION("Simulation", "시뮬레이션"),
    PREFIX_SUM("Prefix Sum", "누적 합"),
    COMBINATORICS("Combinatorics", "조합론"),
    BFS("Breadth-first Search", "너비 우선 탐색"),
    CASE_WORK("Case Work", "많은 조건 분기"),
    SET_MAP("Set / Map", "집합과 맵"),
    BITMASK("Bitmask", "비트마스킹"),
    DFS("Depth-first Search", "깊이 우선 탐색"),
    SHORTEST_PATH("Shortest Path", "최단 경로"),
    SET_MAP_HASHING("Set / Map By Hashing", "해시를 사용한 집합과 맵"),
    DIJKSTRA("Dijkstra's", "데이크스트라"),
    SWEEPING("Sweeping", "스위핑"),
    BACKTRACKING("Backtracking", "백트래킹"),
    DISJOINT_SET("Disjoint Set", "분리 집합"),
    DP_ON_TREES("Dynamic Programming On Trees", "트리에서의 다이나믹 프로그래밍"),
    SET_MAP_TREES("Set / Map By Trees", "트리를 사용한 집합과 맵"),
    PARSING("Parsing", "파싱"),
    PRIORITY_QUEUE("Priority Queue", "우선순위 큐"),
    GAME_THEORY("Game Theory", "게임 이론"),
    PARAMETRIC_SEARCH("Parametric Search", "매개 변수 탐색"),
    DIVIDE_AND_CONQUER("Divide And Conquer", "분할 정복"),
    TWO_POINTER("Two-pointer", "두 포인터"),
    STACK("Stack", "스택"),
    PROBABILITY("Probability Theory", "확률론"),
    PRIMALITY_TEST("Primality Test", "소수 판정"),
    SEGMENT_TREE_LAZY("Segment Tree With Lazy Propagation", "느리게 갱신되는 세그먼트 트리"),
    MAX_FLOW("Maximum Flow", "최대 유량"),
    DP_BITFIELD("Dynamic Programming Using Bitfield", "비트필드를 이용한 다이나믹 프로그래밍"),
    OFFLINE_QUERIES("Offline Queries", "오프라인 쿼리"),
    EXPONENTIATION_BY_SQUARING("Exponentiation By Squaring", "분할 정복을 이용한 거듭제곱"),
    KNAPSACK("Knapsack", "배낭 문제"),
    COORD_COMPRESSION("Value / Coordinate Compression", "값 / 좌표 압축"),
    RECURSION("Recursion", "재귀"),
    ARBITRARY_PRECISION("Arbitrary Precision / Big Integers", "임의 정밀도 / 큰 수 연산"),
    DAG("Directed Acyclic Graph", "방향 비순환 그래프"),
    EUCLIDEAN("Euclidean Algorithm", "유클리드 호제법"),
    MST("Minimum Spanning Tree", "최소 스패닝 트리"),
    CONVEX_HULL("Convex Hull", "볼록 껍질"),
    PRECOMPUTATION("Precomputation", "런타임 전의 전처리"),
    TOPOLOGICAL_SORTING("Topological Sorting", "위상 정렬"),
    SIEVE("Sieve Of Eratosthenes", "에라토스테네스의 체"),
    LINEAR_ALGEBRA("Linear Algebra", "선형대수학"),
    BIPARTITE_MATCHING("Bipartite Matching", "이분 매칭"),
    INCLUSION_EXCLUSION("Inclusion And Exclusion", "포함 배제의 원리"),
    LCA("Lowest Common Ancestor", "최소 공통 조상"),
    SPARSE_TABLE("Sparse Table", "희소 배열"),
    GRID_GRAPH("Grid Graph", "격자 그래프"),
    HASHING("Hashing", "해싱"),
    RANDOMIZATION("Randomization", "무작위화"),
    FLOYD_WARSHALL("Floyd–warshall", "플로이드–워셜"),
    MODULAR_INVERSE("Modular Multiplicative Inverse", "모듈로 곱셈 역원"),
    SCC("Strongly Connected Component", "강한 연결 요소"),
    SMALLER_TO_LARGER("Smaller To Larger Technique", "작은 집합에서 큰 집합으로 합치는 테크닉"),
    LINE_INTERSECTION("Line Segment Intersection Check", "선분 교차 판정"),
    TRACEBACK("Traceback", "역추적"),
    FFT("Fast Fourier Transform", "고속 푸리에 변환"),
    CALCULUS("Calculus", "미적분학"),
    PARITY("Parity", "홀짝성"),
    TRIE("Trie", "트라이"),
    SQRT_DECOMPOSITION("Square Root Decomposition", "제곱근 분할법"),
    DEQUE("Deque", "덱"),
    TERNARY_SEARCH("Ternary Search", "삼분 탐색"),
    GEOMETRY_3D("Geometry; 3d", "3차원 기하학"),
    HEURISTICS("Heuristics", "휴리스틱"),
    SUFFIX_ARRAY("Suffix Array And Lcp Array", "접미사 배열과 lcp 배열"),
    EULER_TOUR("Euler Tour Technique", "오일러 경로 테크닉"),
    SPRAGUE_GRUNDY("Sprague–grundy Theorem", "스프라그–그런디 정리"),
    MCMF("Minimum Cost Maximum Flow", "최소 비용 최대 유량"),
    SLIDING_WINDOW("Sliding Window", "슬라이딩 윈도우"),
    CONVEX_HULL_TRICK("Convex Hull Trick", "볼록 껍질을 이용한 최적화"),
    CENTROID("Centroid", "센트로이드"),
    MEET_IN_THE_MIDDLE("Meet In The Middle", "중간에서 만나기"),
    PYTHAGORAS("Pythagoras Theorem", "피타고라스 정리"),
    PERMUTATION_CYCLE("Permutation Cycle Decomposition", "순열 사이클 분할"),
    BIT_SET("Bit Set", "비트 집합"),
    LIS("Longest Increasing Sequence Problem", "가장 긴 증가하는 부분 수열 문제"),
    KMP("Knuth–morris–pratt", "kmp"),
    PRIME_FACTORIZATION("Prime Factorization", "소인수분해"),
    GAUSSIAN_ELIMINATION("Gaussian Elimination", "가우스 소거법"),
    HLD("Heavy-light Decomposition", "heavy-light 분할"),
    LINEARITY_OF_EXPECTATION("Linearity Of Expectation", "기댓값의 선형성"),
    BIPARTITE_GRAPH("Bipartite Graph", "이분 그래프"),
    POLYGON_AREA("Area Of A Polygon", "다각형의 넓이"),
    MAX_FLOW_MIN_CUT("Max-flow Min-cut Theorem", "최대 유량 최소 컷 정리"),
    CENTROID_DECOMPOSITION("Centroid Decomposition", "센트로이드 분할"),
    DIFFERENCE_ARRAY("Difference Array", "차분 배열 트릭"),
    PHYSICS("Physics", "물리학"),
    ZERO_ONE_BFS("0-1 Bfs", "0-1 너비 우선 탐색"),
    FERMAT_LITTLE("Fermat's Little Theorem", "페르마의 소정리"),
    EULERIAN_PATH("Eulerian Path / Circuit", "오일러 경로"),
    FLOOD_FILL("Flood-fill", "플러드 필"),
    TWO_SAT("2-sat", "2-sat"),
    ARTICULATION_POINTS("Articulation Points And Bridges", "단절점과 단절선"),
    QUEUE("Queue", "큐"),
    TSP("Travelling Salesman Problem", "외판원 순회 문제"),
    PIGEONHOLE("Pigeonhole Principle", "비둘기집 원리"),
    PERSISTENT_SEGMENT_TREE("Persistent Segment Tree", "퍼시스턴트 세그먼트 트리"),
    FUNCTIONAL_GRAPH("Functional Graph", "함수형 그래프"),
    PLANAR_GRAPH("Planar Graph", "평면 그래프"),
    EULER_TOTIENT("Euler Totient Function", "오일러 피 함수"),
    DEQUE_RANGE_MAX("Deque Range Maximum Trick", "덱을 이용한 구간 최댓값 트릭"),
    BICONNECTED_COMPONENT("Biconnected Component", "이중 연결 요소"),
    POINT_IN_CONVEX_POLYGON("Point In Convex Polygon Check", "볼록 다각형 내부의 점 판정"),
    LINKED_LIST("Linked List", "연결 리스트"),
    CRT("Chinese Remainder Theorem", "중국인의 나머지 정리"),
    DIGIT_DP("Digit Dp", "자릿수를 이용한 다이나믹 프로그래밍"),
    GENERATING_FUNCTION("Generating Function", "생성 함수"),
    ANGLE_SORTING("Angle Sorting", "각도 정렬"),
    CACTUS("Cactus", "선인장"),
    REROOTING("Rerooting On Trees", "트리에서의 전방향 다이나믹 프로그래밍"),
    EXTENDED_EUCLIDEAN("Extended Euclidean Algorithm", "확장 유클리드 호제법"),
    MOS("Mo's", "mo's"),
    BELLMAN_FORD("Bellman–ford", "벨만–포드"),
    TREE_DIAMETER("Diameter Of A Tree", "트리의 지름"),
    SPLAY_TREE("Splay Tree", "스플레이 트리"),
    DIVIDE_CONQUER_OPT("Divide And Conquer Optimization", "분할 정복을 사용한 최적화"),
    PARALLEL_BINARY_SEARCH("Parallel Binary Search", "병렬 이분 탐색"),
    FINDING_INVARIANTS("Finding Invariants", "불변량 찾기"),
    MAX_SUBARRAY("Maximum Subarray", "최대 부분 배열 문제"),
    HARMONIC_NUMBER("Harmonic Number", "조화수"),
    HALF_PLANE_INTERSECTION("Half Plane Intersection", "반평면 교집합"),
    ROTATING_CALIPERS("Rotating Calipers", "회전하는 캘리퍼스"),
    EULER_CHARACTERISTIC("Euler Characteristic (χ=v-e+f)", "오일러 지표 (χ=v-e+f)"),
    REGEX("Regular Expression", "정규 표현식"),
    SLOPE_TRICK("Slope Trick", "함수 개형을 이용한 최적화"),
    MULTIDIMENSIONAL_SEGMENT_TREE("Multidimensional Segment Tree", "다차원 세그먼트 트리"),
    SOS_DP("Sum Over Subsets Dynamic Programming", "부분집합의 합 다이나믹 프로그래밍"),
    AHO_CORASICK("Aho-corasick", "아호-코라식"),
    DP_DEQUE("Dynamic Programming Using A Deque", "덱을 이용한 다이나믹 프로그래밍"),
    MANACHER("Manacher's", "매내처"),
    MILLER_RABIN("Miller–rabin", "밀러–라빈 소수 판별법"),
    POLLARD_RHO("Pollard Rho", "폴라드 로"),
    MOBIUS_INVERSION("Möbius Inversion", "뫼비우스 반전 공식"),
    TREE_ISOMORPHISM("Tree Isomorphism", "트리 동형 사상"),
    MERGE_SORT_TREE("Merge Sort Tree", "머지 소트 트리"),
    NUMERICAL_ANALYSIS("Numerical Analysis", "수치해석"),
    LCS("Longest Common Subsequence", "최장 공통 부분 수열 문제"),
    POINT_IN_NON_CONVEX("Point In Non-convex Polygon Check", "오목 다각형 내부의 점 판정"),
    DP_CONNECTION_PROFILE("Dynamic Programming Using Connection Profile", "커넥션 프로파일을 이용한 다이나믹 프로그래밍"),
    RABIN_KARP("Rabin–karp", "라빈–카프"),
    SIMULATED_ANNEALING("Simulated Annealing", "담금질 기법"),
    HALLS_THEOREM("Hall's Theorem", "홀의 결혼 정리"),
    LINK_CUT_TREE("Link/cut Tree", "링크/컷 트리"),
    BERLEKAMP_MASSEY("Berlekamp–massey", "벌리캠프–매시"),
    STATISTICS("Statistics", "통계학"),
    CARTESIAN_TREE("Cartesian Tree", "데카르트 트리"),
    OFFLINE_DYNAMIC_CONNECTIVITY("Offline Dynamic Connectivity", "오프라인 동적 연결성 판정"),
    HUNGARIAN("Hungarian", "헝가리안"),
    Z("Z", "z"),
    ALIENS("Aliens Trick", "aliens 트릭"),
    TREE_COMPRESSION("Tree Compression", "트리 압축"),
    BOOLEAN_OPERATIONS("Boolean Operations On Geometric Objects", "도형에서의 불 연산"),
    LINEAR_PROGRAMMING("Linear Programming", "선형 계획법"),
    LI_CHAO_TREE("Li–chao Tree", "리–차오 트리"),
    VORONOI("Voronoi Diagram", "보로노이 다이어그램"),
    LUCAS("Lucas Theorem", "뤼카 정리"),
    XOR_BASIS("Xor Basis (gf(2))", "배타적 논리합 기저 (gf(2))"),
    DUAL_GRAPH("Dual Graph", "쌍대 그래프"),
    GREEN("Green's Theorem", "그린 정리"),
    CIRCULATION("Circulation", "서큘레이션"),
    DUALITY("Duality", "쌍대성"),
    SEGMENT_TREE_BEATS("Segment Tree Beats", "세그먼트 트리 비츠"),
    POLYNOMIAL_INTERPOLATION("Polynomial Interpolation", "다항식 보간법"),
    GENERAL_MATCHING("General Matching", "일반적인 매칭"),
    MONOTONE_QUEUE_OPT("Monotone Queue Optimization", "단조 큐를 이용한 최적화"),
    MATROID("Matroid", "매트로이드"),
    SUFFIX_TREE("Suffix Tree", "접미사 트리"),
    PICKS_THEOREM("Pick's Theorem", "픽의 정리"),
    LINEAR_RECURRENCE("Linear Recurrence Calculation By Polynomials", "다항식을 이용한 선형점화식 계산"),
    GEOMETRY_HYPER("Geometry; Hyperdimensional", "4차원 이상의 기하학"),
    DISCRETE_LOG("Discrete Logarithm", "이산 로그"),
    MIN_ENCLOSING_CIRCLE("Minimum Enclosing Circle", "최소 외접원"),
    TREE_DECOMPOSITION("Tree Decomposition", "트리 분할"),
    CDQ("Cdq", "cdq 분할 정복"),
    BURNSIDE("Burnside's Lemma", "번사이드 보조정리"),
    DEGREE_SEQUENCE("Degree Sequence", "차수열"),
    TOP_TREE("Top Tree", "탑 트리"),
    BIDIRECTIONAL_SEARCH("Bidirectional Search", "양방향 탐색"),
    DOMINATOR_TREE("Dominator Tree", "도미네이터 트리"),
    DIFFERENTIAL_CRYPTANALYSIS("Differential Cryptanalysis", "차분 공격"),
    UTF8("Utf-8 Inputs", "utf-8 입력 처리"),
    BULLDOZER("Bulldozer Trick", "bulldozer 트릭"),
    PALINDROME_TREE("Palindrome Tree", "회문 트리"),
    DANCING_LINKS("Dancing Links", "춤추는 링크"),
    KNUTH_X("Knuth's X", "크누스 x"),
    STABLE_MARRIAGE("Stable Marriage Problem", "안정 결혼 문제"),
    GRADIENT_DESCENT("Gradient Descent", "경사 하강법"),
    LGV("Lindström–gessel–viennot Lemma", "린드스트롬–게셀–비엔노 보조정리"),
    PISANO("Pisano Period", "피사노 주기"),
    DELAUNAY("Delaunay Triangulation", "델로네 삼각분할"),
    BAYES("Bayes Theorem", "베이즈 정리"),
    DISCRETE_SQRT("Discrete Square Root", "이산 제곱근"),
    ROPE("Rope", "로프"),
    RATIONAL_SUM("Sum Of Floor Of Rational Arithmetic Sequence", "유리 등차수열의 내림 합"),
    KNUTH_OPT("Knuth Optimization", "크누스 최적화"),
    MULTIPOINT_EVAL("Multipoint Evaluation", "다중 대입값 계산"),
    LCS_BITSET("Longest Common Subsequence Using Bit Sets", "비트 집합을 이용한 최장 공통 부분 수열 최적화"),
    HIRSCHBERG("Hirschberg's", "히르쉬버그"),
    CHORDAL_GRAPH("Chordal Graph", "현 그래프"),
    BIRTHDAY("Birthday Problem", "생일 문제"),
    DIRECTED_MST("Directed Minimum Spanning Tree", "유향 최소 스패닝 트리"),
    STOER_WAGNER("Stoer–wagner", "스토어–바그너"),
    LTE("Lifting The Exponent Lemma", "지수승강 보조정리"),
    DIAL("Dial", "다이얼"),
    HACKENBUSH("Hackenbush", "하켄부시 게임"),
    KINETIC_SEGMENT_TREE("Kinetic Segment Tree", "키네틱 세그먼트 트리"),
    BOYER_MOORE("Boyer–moore Majority Vote", "보이어–무어 다수결 투표"),
    RED_BLACK_TREE("Red-black Tree", "레드-블랙 트리"),
    UNKNOWN("Unknown", "알 수 없음");

    companion object {
        /**
         * 한글 태그 이름을 받아서 해당하는 ProblemCategory Enum을 반환한다.
         * 매칭되지 않으면 UNKNOWN을 반환한다.
         * 대소문자 무시 및 공백 제거 후 비교하여 매핑 정확도 향상
         *
         * @param korean 한글 태그 이름
         * @return 해당하는 ProblemCategory (매칭 안 되면 UNKNOWN)
         */
        fun fromKorean(korean: String): ProblemCategory {
            // 대소문자 무시 및 공백 제거 후 비교하여 매핑 정확도 향상
            val normalizedInput = korean.replace(" ", "").lowercase()

            return entries.find {
                it.koreanName.replace(" ", "").lowercase() == normalizedInput
            } ?: UNKNOWN
        }
    }
}
